Cinema Management System/Cinemang/Controllers/DeleteCinemaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Cinemang.Controllers
{
    public class DeleteCinemaController : Controller
    {
        // GET: DeleteCinema
        public ActionResult Index()
        {
            Models.CinemangData db = new Models.CinemangData();
            List<Models.Cinema> cinemalist = db.Cinema.ToList();
            return View(cinemalist);
        }
        [HttpPost]
        public ActionResult Index(string searchString)
        {
            Models.CinemangData db = new Models.CinemangData();
            var cinemas = from m in db.Cinema
                         select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                cinemas = cinemas.Where(s => s.cLocation.Contains(searchString));
            }

            return View(cinemas);
        }

        public ActionResult Delete(int? id)
        {
            Models.CinemangData db = new Models.CinemangData();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Models.Cinema cinema = db.Cinema.Find(id);
            if (cinema == null)
            {
                return HttpNotFound();
            }
            return View(cinema);
        }

  
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Models.CinemangData db = new Models.CinemangData();
            Models.Cinema cinema = db.Cinema.Find(id);
            db.Cinema.Remove(cinema);
            db.SaveChanges();
            return RedirectToAction("Index", "ListCinemas");
        }
    }
}

Cinema Management System/Cinemang/Views/DeleteCinema/Delete.cshtml
@model Cinemang.Models.Cinema

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_StaffHomeLayout.cshtml";
}


<div class="header">
    <h2>
        Sinemayı Sil
        <small>Seçmiş olduğunuz sinemaya ait bilgileri görüntüleyerek isterseniz filmi silebilirsiniz.</small>
    </h2>
    <ul class="header-dropdown m-r--5">
        <li class="dropdown">
            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <i class="material-icons">more_vert</i>
            </a>
            <ul class="dropdown-menu pull-right">
                <li><a href="javascript:void(0);">Action</a></li>
                <li><a href="javascript:void(0);">Another action</a></li>
                <li><a href="javascript:void(0);">Something else here</a></li>
            </ul>
        </li>
    </ul>
</div>
<div class="body table-responsive">
    <h3>Aşağıda listelenen bilgilere ait kaydı silmek istediğinizden emin misiniz?</h3>
    <div>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.cName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.cName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.cAddress)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.cAddress)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.cLocation)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.cLocation)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">

                @Html.ActionLink("Listeye Geri Dön", "Index", "ListCinemas")|
                <input type="submit" value="Sil" class="btn btn-default" />

            </div>
        }
    </div>

</div>

Cinema Management System/Cinemang/Views/DeleteCinema/Index.cshtml
@model IEnumerable<Cinemang.Models.Cinema>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_StaffHomeLayout.cshtml";
}

<div class="header">
    <h2>
        Sinemaları Kaldır
        <small>Sistemde bulunan herhangi bir sinemayı arayarak isterseniz silebilirsiniz.</small>
    </h2>
    <ul class="header-dropdown m-r--5">
        <li class="dropdown">
            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <i class="material-icons">more_vert</i>
            </a>
            <ul class="dropdown-menu pull-right">
                <li><a href="javascript:void(0);">Action</a></li>
                <li><a href="javascript:void(0);">Another action</a></li>
                <li><a href="javascript:void(0);">Something else here</a></li>
            </ul>
        </li>
    </ul>
</div>
<div class="body table-responsive">
    <p>
    <p>
        @using (Html.BeginForm())
        {
        <p>
            Aramak İstediğiniz Sinemanın Lokasyonunu Giriniz: @Html.TextBox("SearchString")
            <input type="submit" value="Ara" />
        </p>
    }
        </p>
        </p>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.cName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.cAddress)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.cLocation)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.cName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.cAddress)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.cLocation)
                    </td>
                    

                    <td>
                        @Html.ActionLink("Sil", "Delete", "DeleteCinema", new { id = item.c_id }, null)
                    </td>
                </tr>
            }

        </table>
    </div>